name: Question
description: Ask a question about Coreverse Engine.
title: "[Question]: "
labels:
  - question

body:
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please describe your question in detail.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
