name: Rust

on:
  workflow_call:

permissions:
  contents: read

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Bootstrap
        shell: bash
        run: |
          chmod +x devkit/scripts/setup/shell/bootstrap.sh
          devkit/scripts/setup/shell/bootstrap.sh

      - uses: Swatinem/rust-cache@v2

      - name: Cargo Check
        run: cargo check --workspace --all-features

      - name: Cargo Test
        run: cargo test --workspace --all-features

      - name: Clippy
        run: cargo clippy --workspace --all-features
