name: Rust

on:
  workflow_call:

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Cargo Check
        run: cargo check --workspace --all-features

      - name: Cargo Test
        run: cargo test --workspace --all-features

      - name: Clippy
        run: cargo clippy --workspace --all-features
